# Generated by Django 4.2.3 on 2023-07-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0001_initial'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementMateriel',
            fields=[
                ('idMouvement', models.AutoField(primary_key=True, serialize=False)),
                ('dateMouvement', models.DateField()),
                ('dateRetour', models.DateField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=200)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.materiel')),
            ],
        ),
    ]
