version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=webpickdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
    driver: local
#docker-compose up --build 