# Generated by Django 4.2.3 on 2023-07-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('nomCategory', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('idMateriel', models.AutoField(primary_key=True, serialize=False)),
                ('nomMateriel', models.CharField(max_length=100)),
                ('NumSerie', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('idSousCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nomSousCategory', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.categorie')),
            ],
        ),
    ]
