# Generated by Django 4.2.3 on 2023-07-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_remove_materiel_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
