# Generated by Django 4.2.3 on 2023-07-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
        ('materiels', '0002_materiel_sous_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fournisseur.fournisseur'),
        ),
    ]
