# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0005_demandemateriel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandemateriel',
            old_name='date_debut_utilisation',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='demandemateriel',
            old_name='employe',
            new_name='demandeur',
        ),
    ]
