# Generated by Django 4.2.3 on 2023-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0007_demandemateriel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemateriel',
            name='status',
            field=models.CharField(default='pas encore traite', max_length=100),
        ),
    ]
