# Generated by Django 4.2.3 on 2023-07-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArticle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_article', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.AutoField(primary_key=True, serialize=False)),
                ('date_facture', models.DateField()),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ville', models.CharField(max_length=30)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
            ],
        ),
    ]
