# Generated by Django 4.2.3 on 2023-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
    ]
