# Generated by Django 3.2.20 on 2023-07-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0008_alter_demandemateriel_status'),
        ('facture', '0002_facture_facture_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nom_article',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='article',
            name='materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiels.materiel'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.article'),
        ),
    ]
