# Generated by Django 4.2.3 on 2023-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="role_target",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "user")],
                default="ADMIN",
                max_length=30,
            ),
        ),
    ]
