# Generated by Django 4.2.3 on 2023-07-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_role_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="theme",
            field=models.CharField(default="pannes", max_length=100),
        ),
    ]
