# Generated by Django 4.2.3 on 2023-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_ticket_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file',
        ),
        migrations.AddField(
            model_name='ticket',
            name='files',
            field=models.ManyToManyField(blank=True, to='demandes.fileupload'),
        ),
    ]
