# Generated by Django 4.2.4 on 2023-08-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
