# Generated by Django 4.2.3 on 2023-08-10 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiels', '0009_demande_materiel'),
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_panne', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=130)),
                ('file', models.FileField(blank=True, null=True, upload_to='filemaintenance/')),
                ('materiel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiels.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Notesmaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesmaintenance', to='maintenance.maintenance')),
            ],
        ),
    ]
