# Generated by Django 4.2.4 on 2023-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='filemaintenance/')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='file',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_reparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='files',
            field=models.ManyToManyField(blank=True, to='maintenance.maintenancefile'),
        ),
        migrations.AddField(
            model_name='notesmaintenance',
            name='files',
            field=models.ManyToManyField(blank=True, to='maintenance.maintenancefile'),
        ),
    ]
